import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import Link from "next/link";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="font-sans">
        <header className="bg-green-700 text-white p-4 flex gap-4">
          <Link href="/">Home</Link>
          <Link href="/scrap-my-car">Scrap My Car</Link>
          <Link href="/scrap-my-van">Scrap My Van</Link>
          <Link href="/blog">Blog</Link>
          <Link href="/areas-we-cover">Areas We Cover</Link>
        </header>
        <main className="p-8">{children}</main>
      </body>
    </html>
  );
}
